CREATE DATABASE CLICKCLOUD;

CREATE USER 'clickcloud'@'%' IDENTIFIED BY '{PASSWORD}';

GRANT ALL PRIVILEGES ON CLICKCLOUD.* to 'clickcloud'@'%';

SHOW GRANTS FOR 'clickcloud'@'%';

CREATE TABLE WEATHER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY VARCHAR(20) NOT NULL,
    TEMP INT NOT NULL
);

INSERT INTO WEATHER (CITY, TEMP) VALUES ('Seoul', 10);

SELECT * FROM WEATHER;

DROP TABLE WEATHER;

SHOW TABLES;