DROP TABLE WEATHER;
CREATE TABLE WEATHER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY VARCHAR(20) NOT NULL,
    TEMP INT NOT NULL
);

INSERT INTO WEATHER (CITY, TEMP) VALUES ('Seoul', 10);

SELECT * FROM WEATHER;