INSERT INTO countries VALUES ('AF', 'Afghanistan', 'AS');
INSERT INTO countries VALUES ('AX', 'Aland Islands', 'EU');
INSERT INTO countries VALUES ('AL', 'Albania', 'EU');
INSERT INTO countries VALUES ('DZ', 'Algeria', 'AF');
INSERT INTO countries VALUES ('AS', 'American Samoa', 'OC');
INSERT INTO countries VALUES ('AD', 'Andorra', 'EU');
INSERT INTO countries VALUES ('AO', 'Angola', 'AF');
INSERT INTO countries VALUES ('AI', 'Anguilla', 'NA');
INSERT INTO countries VALUES ('AQ', 'Antarctica', 'AN');
INSERT INTO countries VALUES ('AG', 'Antigua and Barbuda', 'NA');
INSERT INTO countries VALUES ('AR', 'Argentina', 'SA');
INSERT INTO countries VALUES ('AM', 'Armenia', 'AS');
INSERT INTO countries VALUES ('AW', 'Aruba', 'NA');
INSERT INTO countries VALUES ('AU', 'Australia', 'OC');
INSERT INTO countries VALUES ('AT', 'Austria', 'EU');
INSERT INTO countries VALUES ('AZ', 'Azerbaijan', 'AS');
INSERT INTO countries VALUES ('BS', 'Bahamas', 'NA');
INSERT INTO countries VALUES ('BH', 'Bahrain', 'AS');
INSERT INTO countries VALUES ('BD', 'Bangladesh', 'AS');
INSERT INTO countries VALUES ('BB', 'Barbados', 'NA');
INSERT INTO countries VALUES ('BY', 'Belarus', 'EU');
INSERT INTO countries VALUES ('BE', 'Belgium', 'EU');
INSERT INTO countries VALUES ('BZ', 'Belize', 'NA');
INSERT INTO countries VALUES ('BJ', 'Benin', 'AF');
INSERT INTO countries VALUES ('BM', 'Bermuda', 'NA');
INSERT INTO countries VALUES ('BT', 'Bhutan', 'AS');
INSERT INTO countries VALUES ('BO', 'Bolivia', 'SA');
INSERT INTO countries VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba', 'NA');
INSERT INTO countries VALUES ('BA', 'Bosnia and Herzegovina', 'EU');
INSERT INTO countries VALUES ('BW', 'Botswana', 'AF');
INSERT INTO countries VALUES ('BV', 'Bouvet Island', 'AN');
INSERT INTO countries VALUES ('BR', 'Brazil', 'SA');
INSERT INTO countries VALUES ('IO', 'British Indian Ocean Territory', 'AS');
INSERT INTO countries VALUES ('BN', 'Brunei', 'AS');
INSERT INTO countries VALUES ('BG', 'Bulgaria', 'EU');
INSERT INTO countries VALUES ('BF', 'Burkina Faso', 'AF');
INSERT INTO countries VALUES ('BI', 'Burundi', 'AF');
INSERT INTO countries VALUES ('KH', 'Cambodia', 'AS');
INSERT INTO countries VALUES ('CM', 'Cameroon', 'AF');
INSERT INTO countries VALUES ('CA', 'Canada', 'NA');
INSERT INTO countries VALUES ('CV', 'Cape Verde', 'AF');
INSERT INTO countries VALUES ('KY', 'Cayman Islands', 'NA');
INSERT INTO countries VALUES ('CF', 'Central African Republic', 'AF');
INSERT INTO countries VALUES ('TD', 'Chad', 'AF');
INSERT INTO countries VALUES ('CL', 'Chile', 'SA');
INSERT INTO countries VALUES ('CN', 'China', 'AS');
INSERT INTO countries VALUES ('CX', 'Christmas Island', 'AS');
INSERT INTO countries VALUES ('CC', 'Cocos (Keeling) Islands', 'AS');
INSERT INTO countries VALUES ('CO', 'Colombia', 'SA');
INSERT INTO countries VALUES ('KM', 'Comoros', 'AF');
INSERT INTO countries VALUES ('CG', 'Congo', 'AF');
INSERT INTO countries VALUES ('CD', 'Congo, Democratic Republic of the', 'AF');
INSERT INTO countries VALUES ('CK', 'Cook Islands', 'OC');
INSERT INTO countries VALUES ('CR', 'Costa Rica', 'NA');
INSERT INTO countries VALUES ('CI', 'Ivory Coast', 'AF');
INSERT INTO countries VALUES ('HR', 'Croatia', 'EU');
INSERT INTO countries VALUES ('CU', 'Cuba', 'NA');
INSERT INTO countries VALUES ('CW', 'Curacao', 'NA');
INSERT INTO countries VALUES ('CY', 'Cyprus', 'AS');
INSERT INTO countries VALUES ('CZ', 'Czech Republic', 'EU');
INSERT INTO countries VALUES ('DK', 'Denmark', 'EU');
INSERT INTO countries VALUES ('DJ', 'Djibouti', 'AF');
INSERT INTO countries VALUES ('DM', 'Dominica', 'NA');
INSERT INTO countries VALUES ('DO', 'Dominican Republic', 'NA');
INSERT INTO countries VALUES ('EC', 'Ecuador', 'SA');
INSERT INTO countries VALUES ('EG', 'Egypt', 'AF');
INSERT INTO countries VALUES ('SV', 'El Salvador', 'NA');
INSERT INTO countries VALUES ('GQ', 'Equatorial Guinea', 'AF');
INSERT INTO countries VALUES ('ER', 'Eritrea', 'AF');
INSERT INTO countries VALUES ('EE', 'Estonia', 'EU');
INSERT INTO countries VALUES ('ET', 'Ethiopia', 'AF');
INSERT INTO countries VALUES ('FK', 'Falkland Islands (Malvinas)', 'SA');
INSERT INTO countries VALUES ('FO', 'Faroe Islands', 'EU');
INSERT INTO countries VALUES ('FJ', 'Fiji', 'OC');
INSERT INTO countries VALUES ('FI', 'Finland', 'EU');
INSERT INTO countries VALUES ('FR', 'France', 'EU');
INSERT INTO countries VALUES ('GF', 'French Guiana', 'SA');
INSERT INTO countries VALUES ('PF', 'French Polynesia', 'OC');
INSERT INTO countries VALUES ('TF', 'French Southern Territories', 'AN');
INSERT INTO countries VALUES ('GA', 'Gabon', 'AF');
INSERT INTO countries VALUES ('GM', 'Gambia', 'AF');
INSERT INTO countries VALUES ('GE', 'Georgia', 'AS');
INSERT INTO countries VALUES ('DE', 'Germany', 'EU');
INSERT INTO countries VALUES ('GH', 'Ghana', 'AF');
INSERT INTO countries VALUES ('GI', 'Gibraltar', 'EU');
INSERT INTO countries VALUES ('GR', 'Greece', 'EU');
INSERT INTO countries VALUES ('GL', 'Greenland', 'NA');
INSERT INTO countries VALUES ('GD', 'Grenada', 'NA');
INSERT INTO countries VALUES ('GP', 'Guadeloupe', 'NA');
INSERT INTO countries VALUES ('GU', 'Guam', 'OC');
INSERT INTO countries VALUES ('GT', 'Guatemala', 'NA');
INSERT INTO countries VALUES ('GG', 'Guernsey', 'EU');
INSERT INTO countries VALUES ('GN', 'Guinea', 'AF');
INSERT INTO countries VALUES ('GW', 'Guinea-Bissau', 'AF');
INSERT INTO countries VALUES ('GY', 'Guyana', 'SA');
INSERT INTO countries VALUES ('HT', 'Haiti', 'NA');
INSERT INTO countries VALUES ('HM', 'Heard Island and McDonald Islands', 'AN');
INSERT INTO countries VALUES ('VA', 'Holy See (Vatican City State)', 'EU');
INSERT INTO countries VALUES ('HN', 'Honduras', 'NA');
INSERT INTO countries VALUES ('HK', 'Hong Kong', 'AS');
INSERT INTO countries VALUES ('HU', 'Hungary', 'EU');
INSERT INTO countries VALUES ('IS', 'Iceland', 'EU');
INSERT INTO countries VALUES ('IN', 'India', 'AS');
INSERT INTO countries VALUES ('ID', 'Indonesia', 'AS');
INSERT INTO countries VALUES ('IR', 'Iran, Islamic Republic of', 'AS');
INSERT INTO countries VALUES ('IQ', 'Iraq', 'AS');
INSERT INTO countries VALUES ('IE', 'Ireland', 'EU');
INSERT INTO countries VALUES ('IM', 'Isle of Man', 'EU');
INSERT INTO countries VALUES ('IL', 'Israel', 'AS');
INSERT INTO countries VALUES ('IT', 'Italy', 'EU');
INSERT INTO countries VALUES ('JM', 'Jamaica', 'NA');
INSERT INTO countries VALUES ('JP', 'Japan', 'AS');
INSERT INTO countries VALUES ('JE', 'Jersey', 'EU');
INSERT INTO countries VALUES ('JO', 'Jordan', 'AS');
INSERT INTO countries VALUES ('KZ', 'Kazakhstan', 'AS');
INSERT INTO countries VALUES ('KE', 'Kenya', 'AF');
INSERT INTO countries VALUES ('KI', 'Kiribati', 'OC');
INSERT INTO countries VALUES ('KP', "Korea, Democratic People's Republic of", 'AS');
INSERT INTO countries VALUES ('KR', 'Korea, Republic of', 'AS');
INSERT INTO countries VALUES ('KW', 'Kuwait', 'AS');
INSERT INTO countries VALUES ('KG', 'Kyrgyzstan', 'AS');
INSERT INTO countries VALUES ('LA', "Lao People's Democratic Republic", 'AS');
INSERT INTO countries VALUES ('LV', 'Latvia', 'EU');
INSERT INTO countries VALUES ('LB', 'Lebanon', 'AS');
INSERT INTO countries VALUES ('LS', 'Lesotho', 'AF');
INSERT INTO countries VALUES ('LR', 'Liberia', 'AF');
INSERT INTO countries VALUES ('LY', 'Libya', 'AF');
INSERT INTO countries VALUES ('LI', 'Liechtenstein', 'EU');
INSERT INTO countries VALUES ('LT', 'Lithuania', 'EU');
INSERT INTO countries VALUES ('LU', 'Luxembourg', 'EU');
INSERT INTO countries VALUES ('MO', 'Macao', 'AS');
INSERT INTO countries VALUES ('MK', 'Macedonia, the former Yugoslav Republic of', 'EU');
INSERT INTO countries VALUES ('MG', 'Madagascar', 'AF');
INSERT INTO countries VALUES ('MW', 'Malawi', 'AF');
INSERT INTO countries VALUES ('MY', 'Malaysia', 'AS');
INSERT INTO countries VALUES ('MV', 'Maldives', 'AS');
INSERT INTO countries VALUES ('ML', 'Mali', 'AF');
INSERT INTO countries VALUES ('MT', 'Malta', 'EU');
INSERT INTO countries VALUES ('MH', 'Marshall Islands', 'OC');
INSERT INTO countries VALUES ('MQ', 'Martinique', 'NA');
INSERT INTO countries VALUES ('MR', 'Mauritania', 'AF');
INSERT INTO countries VALUES ('MU', 'Mauritius', 'AF');
INSERT INTO countries VALUES ('YT', 'Mayotte', 'AF');
INSERT INTO countries VALUES ('MX', 'Mexico', 'NA');
INSERT INTO countries VALUES ('FM', 'Micronesia, Federated States of', 'OC');
INSERT INTO countries VALUES ('MD', 'Moldova, Republic of', 'EU');
INSERT INTO countries VALUES ('MC', 'Monaco', 'EU');
INSERT INTO countries VALUES ('MN', 'Mongolia', 'AS');
INSERT INTO countries VALUES ('ME', 'Montenegro', 'EU');
INSERT INTO countries VALUES ('MS', 'Montserrat', 'NA');
INSERT INTO countries VALUES ('MA', 'Morocco', 'AF');
INSERT INTO countries VALUES ('MZ', 'Mozambique', 'AF');
INSERT INTO countries VALUES ('MM', 'Myanmar', 'AS');
INSERT INTO countries VALUES ('NA', 'Namibia', 'AF');
INSERT INTO countries VALUES ('NR', 'Nauru', 'OC');
INSERT INTO countries VALUES ('NP', 'Nepal', 'AS');
INSERT INTO countries VALUES ('NL', 'Netherlands', 'EU');
INSERT INTO countries VALUES ('NC', 'New Caledonia', 'OC');
INSERT INTO countries VALUES ('NZ', 'New Zealand', 'OC');
INSERT INTO countries VALUES ('NI', 'Nicaragua', 'NA');
INSERT INTO countries VALUES ('NE', 'Niger', 'AF');
INSERT INTO countries VALUES ('NG', 'Nigeria', 'AF');
INSERT INTO countries VALUES ('NU', 'Niue', 'OC');
INSERT INTO countries VALUES ('NF', 'Norfolk Island', 'OC');
INSERT INTO countries VALUES ('MP', 'Northern Mariana Islands', 'OC');
INSERT INTO countries VALUES ('NO', 'Norway', 'EU');
INSERT INTO countries VALUES ('OM', 'Oman', 'AS');
INSERT INTO countries VALUES ('PK', 'Pakistan', 'AS');
INSERT INTO countries VALUES ('PW', 'Palau', 'OC');
INSERT INTO countries VALUES ('PS', 'Palestinian Territory, Occupied', 'AS');
INSERT INTO countries VALUES ('PA', 'Panama', 'NA');
INSERT INTO countries VALUES ('PG', 'Papua New Guinea', 'OC');
INSERT INTO countries VALUES ('PY', 'Paraguay', 'SA');
INSERT INTO countries VALUES ('PE', 'Peru', 'SA');
INSERT INTO countries VALUES ('PH', 'Philippines', 'AS');
INSERT INTO countries VALUES ('PN', 'Pitcairn', 'OC');
INSERT INTO countries VALUES ('PL', 'Poland', 'EU');
INSERT INTO countries VALUES ('PT', 'Portugal', 'EU');
INSERT INTO countries VALUES ('PR', 'Puerto Rico', 'NA');
INSERT INTO countries VALUES ('QA', 'Qatar', 'AS');
INSERT INTO countries VALUES ('RE', 'Reunion', 'AF');
INSERT INTO countries VALUES ('RO', 'Romania', 'EU');
INSERT INTO countries VALUES ('RU', 'Russian Federation', 'EU');
INSERT INTO countries VALUES ('RW', 'Rwanda', 'AF');
INSERT INTO countries VALUES ('BL', 'Saint Barthelemy', 'NA');
INSERT INTO countries VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'AF');
INSERT INTO countries VALUES ('KN', 'Saint Kitts and Nevis', 'NA');
INSERT INTO countries VALUES ('LC', 'Saint Lucia', 'NA');
INSERT INTO countries VALUES ('MF', 'Saint Martin (French part)', 'NA');
INSERT INTO countries VALUES ('PM', 'Saint Pierre and Miquelon', 'NA');
INSERT INTO countries VALUES ('VC', 'Saint Vincent and the Grenadines', 'NA');
INSERT INTO countries VALUES ('WS', 'Samoa', 'OC');
INSERT INTO countries VALUES ('SM', 'San Marino', 'EU');
INSERT INTO countries VALUES ('ST', 'Sao Tome and Principe', 'AF');
INSERT INTO countries VALUES ('SA', 'Saudi Arabia', 'AS');
INSERT INTO countries VALUES ('SN', 'Senegal', 'AF');
INSERT INTO countries VALUES ('RS', 'Serbia', 'EU');
INSERT INTO countries VALUES ('SC', 'Seychelles', 'AF');
INSERT INTO countries VALUES ('SL', 'Sierra Leone', 'AF');
INSERT INTO countries VALUES ('SG', 'Singapore', 'AS');
INSERT INTO countries VALUES ('SX', 'Sint Maarten (Dutch part)', 'NA');
INSERT INTO countries VALUES ('SK', 'Slovakia', 'EU');
INSERT INTO countries VALUES ('SI', 'Slovenia', 'EU');
INSERT INTO countries VALUES ('SB', 'Solomon Islands', 'OC');
INSERT INTO countries VALUES ('SO', 'Somalia', 'AF');
INSERT INTO countries VALUES ('ZA', 'South Africa', 'AF');
INSERT INTO countries VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'AN');
INSERT INTO countries VALUES ('SS', 'South Sudan', 'AF');
INSERT INTO countries VALUES ('ES', 'Spain', 'EU');
INSERT INTO countries VALUES ('LK', 'Sri Lanka', 'AS');
INSERT INTO countries VALUES ('SD', 'Sudan', 'AF');
INSERT INTO countries VALUES ('SR', 'Suriname', 'SA');
INSERT INTO countries VALUES ('SJ', 'Svalbard and Jan Mayen', 'EU');
INSERT INTO countries VALUES ('SZ', 'Swaziland', 'AF');
INSERT INTO countries VALUES ('SE', 'Sweden', 'EU');
INSERT INTO countries VALUES ('CH', 'Switzerland', 'EU');
INSERT INTO countries VALUES ('SY', 'Syrian Arab Republic', 'AS');
INSERT INTO countries VALUES ('TW', 'Taiwan, Province of China', 'AS');
INSERT INTO countries VALUES ('TJ', 'Tajikistan', 'AS');
INSERT INTO countries VALUES ('TZ', 'Tanzania, United Republic of', 'AF');
INSERT INTO countries VALUES ('TH', 'Thailand', 'AS');
INSERT INTO countries VALUES ('TL', 'Timor-Leste', 'AS');
INSERT INTO countries VALUES ('TG', 'Togo', 'AF');
INSERT INTO countries VALUES ('TK', 'Tokelau', 'OC');
INSERT INTO countries VALUES ('TO', 'Tonga', 'OC');
INSERT INTO countries VALUES ('TT', 'Trinidad and Tobago', 'NA');
INSERT INTO countries VALUES ('TN', 'Tunisia', 'AF');
INSERT INTO countries VALUES ('TR', 'Turkey', 'AS');
INSERT INTO countries VALUES ('TM', 'Turkmenistan', 'AS');
INSERT INTO countries VALUES ('TC', 'Turks and Caicos Islands', 'NA');
INSERT INTO countries VALUES ('TV', 'Tuvalu', 'OC');
INSERT INTO countries VALUES ('UG', 'Uganda', 'AF');
INSERT INTO countries VALUES ('UA', 'Ukraine', 'EU');
INSERT INTO countries VALUES ('AE', 'United Arab Emirates', 'AS');
INSERT INTO countries VALUES ('GB', 'United Kingdom', 'EU');
INSERT INTO countries VALUES ('US', 'United States', 'NA');
INSERT INTO countries VALUES ('UM', 'United States Minor Outlying Islands', 'OC');
INSERT INTO countries VALUES ('UY', 'Uruguay', 'SA');
INSERT INTO countries VALUES ('UZ', 'Uzbekistan', 'AS');
INSERT INTO countries VALUES ('VU', 'Vanuatu', 'OC');
INSERT INTO countries VALUES ('VE', 'Venezuela, Bolivarian Republic of', 'SA');
INSERT INTO countries VALUES ('VN', 'Viet Nam', 'AS');
INSERT INTO countries VALUES ('VG', 'Virgin Islands, British', 'NA');
INSERT INTO countries VALUES ('VI', 'Virgin Islands, U.S.', 'NA');
INSERT INTO countries VALUES ('WF', 'Wallis and Futuna', 'OC');
INSERT INTO countries VALUES ('EH', 'Western Sahara', 'AF');
INSERT INTO countries VALUES ('YE', 'Yemen', 'AS');
INSERT INTO countries VALUES ('ZM', 'Zambia', 'AF');
INSERT INTO countries VALUES ('ZW', 'Zimbabwe', 'AF');